package co.edu.unicauca.mvc.vistas.evaluar;

import co.edu.unicauca.mvc.accesoADatos.RepositorioConferenciaSqlite;
import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;
import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoConferencias;
import co.edu.unicauca.mvc.modelos.Articulo;
import co.edu.unicauca.mvc.modelos.Conferencia;
import co.edu.unicauca.mvc.vistas.GUIOpciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author earea
 */
public class panelArticulosAsignados extends javax.swing.JPanel {

    private final ServicioAlmacenamientoArticulos objServicioArticulos;
    /**
     * Creates new form Principal
     * @param objServicioArticulos
     */
    public panelArticulosAsignados(ServicioAlmacenamientoArticulos objServicioArticulos) {
        initComponents();
        this.objServicioArticulos = objServicioArticulos;
        mostrarConferencias();
    }

    // Obtención de conferencias y agrega los botones dinámicamente
    private void mostrarConferencias() {
        List<Articulo> articulos = objServicioArticulos.listarArticulos();

        jPanel2.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = GridBagConstraints.RELATIVE;
        gbc.insets = new Insets(10, 0, 10, 0);  // Espacio entre los botones
        gbc.anchor = GridBagConstraints.CENTER; // Centramos los botones

        for (Articulo articulo : articulos) {
            JButton btnConferencia = new JButton(articulo.getTitulo());
            espacioConfes.add(btnConferencia); 
            
            // Establecemos el tamaño y el estilo de los botones
            btnConferencia.setPreferredSize(new Dimension(200, 40)); // Tamaño más pequeño para los botones
            btnConferencia.setBackground(Color.WHITE);
            btnConferencia.setOpaque(true);
            btnConferencia.setBorder(BorderFactory.createLineBorder(new Color(143, 142, 142), 2, true)); // Borde redondeado

            // Efecto hover para cambiar el color cuando el mouse está sobre el botón
            btnConferencia.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btnConferencia.setBackground(new Color(145, 173, 180)); // Cambia color al pasar mouse
                    btnConferencia.setForeground(Color.WHITE); // Cambia color del texto
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btnConferencia.setBackground(Color.WHITE); // Vuelve al color blanco
                    btnConferencia.setForeground(Color.BLACK); // Vuelve el texto al color negro
                }
            });

            // Añadimos el botón al panel
            jPanel2.add(btnConferencia, gbc);

            // Añadimos acción para redirigir al panel de detalles específicos
            btnConferencia.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    GUIOpciones gui = (GUIOpciones) getTopLevelAncestor(); // Obtenemos la referencia de la ventana principal
                    gui.mostrarPanel(new panelArticuloEspecifico(articulo.getTitulo()));
                }
            });
        }

        // Refrescamos el panel
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    // Método que redirige al panel de detalles específicos de una conferencia
    private void mostrarPanelConferenciaEspecifica(Conferencia conferencia) {
        // Aquí debes usar el método que cambia de panel en tu GUI principal
        // Por ejemplo, si estás en el contexto de GUIOpciones, puedes hacer:
        GUIOpciones gui = (GUIOpciones) getTopLevelAncestor(); // Obtenemos la referencia de la ventana principal
        gui.mostrarPanel(new panelArticuloEspecifico(conferencia.getNombre())); // Mostramos el panel con los detalles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioConfes = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));
        setPreferredSize(new java.awt.Dimension(620, 400));
        setRequestFocusEnabled(false);

        espacioConfes.setBackground(new java.awt.Color(236, 236, 236));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setText("Articulos Asignados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout espacioConfesLayout = new javax.swing.GroupLayout(espacioConfes);
        espacioConfes.setLayout(espacioConfesLayout);
        espacioConfesLayout.setHorizontalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(150, 150, 150))
        );
        espacioConfesLayout.setVerticalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioConfes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
