package co.edu.unicauca.mvc.vistas.evaluar;

import co.edu.unicauca.mvc.vistas.GUIOpciones;
import co.edu.unicauca.mvc.vistas.evaluar.panelConferenciaEspecifica;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author earea
 */
public class panelConferenciasAsignadas extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public panelConferenciasAsignadas() {
        initComponents();
        mostrarConferencias();
    }
    
    // Obtención de conferencias y agrega los botones dinámicamente
    private void mostrarConferencias() {
        // Esto después debe venir de la base de datos
        List<String> conferencias = List.of("Conferencia A", "Conferencia B", "Conferencia C");

        // Ajustamos el layout para mostrar los botones en una columna
        espacioConfes.setLayout(new GridLayout(0, 1, 10, 10));

        for (String conferencia : conferencias) {
            JButton btnConferencia = new JButton(conferencia);
            espacioConfes.add(btnConferencia); 

            // Añadir un ActionListener para manejar el clic en cada botón
            btnConferencia.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    mostrarPanelConferenciaEspecifica(conferencia);
                }
            });
        }
        espacioConfes.revalidate();
        espacioConfes.repaint();
    }

    // Método que redirige al panel de detalles específicos de una conferencia
    private void mostrarPanelConferenciaEspecifica(String conferencia) {
        // Aquí debes usar el método que cambia de panel en tu GUI principal
        // Por ejemplo, si estás en el contexto de GUIOpciones, puedes hacer:
        GUIOpciones gui = (GUIOpciones) getTopLevelAncestor(); // Obtenemos la referencia de la ventana principal
        gui.mostrarPanel(new panelConferenciaEspecifica(conferencia)); // Mostramos el panel con los detalles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioConfes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(236, 236, 236));
        setPreferredSize(new java.awt.Dimension(620, 400));
        setRequestFocusEnabled(false);

        espacioConfes.setBackground(new java.awt.Color(236, 236, 236));

        jLabel1.setText("Conferencias Asignadas");

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout espacioConfesLayout = new javax.swing.GroupLayout(espacioConfes);
        espacioConfes.setLayout(espacioConfesLayout);
        espacioConfesLayout.setHorizontalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGroup(espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(espacioConfesLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE))
                    .addGroup(espacioConfesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        espacioConfesLayout.setVerticalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioConfes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
